service: loggingtest

provider:
  name: aws
  runtime: nodejs12.x

functions:
  test:
    handler: combined/handler.run
    role: loggingRole
    events:
      - http:
          path: test/{runs}/{delay}/{write}
          method: get
      - http:
          path: test/{runs}/{delay}
          method: get

  logging:
    handler: with_logging/handler.run
    role: loggingRole
    events:
      - http:
          path: logging/
          method: get
    environment:
      iterations: 100

  lw_logging:
    handler: with_lw_logging/handler.run
    role: loggingRole
    events:
      - http:
          path: lwlogging/
          method: get
    environment:
      iterations: 100

  no_logging:
    handler: without_logging/handler.run
    role: loggingRole
    events:
      - http:
          path: nologging/
          method: get
    environment:
      iterations: 100

resources:
  Resources:
    loggingRole: ${file(security/roles/loggingRole.yml)}
